---
- name: SONiC Interface Naming
  hosts: datacenter
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:
    - name: "Configure description for interface in native name"
      dellemc.enterprise_sonic.sonic_config:
        commands:
          - description Ethernet0
        parents:
          - interface Ethernet0

    # Same prompt and answer for cli "no interface-naming standard"
    - name: "Configure cli with prompts on SONiC device"
      dellemc.enterprise_sonic.sonic_config:
        commands:
          - command: "interface-naming standard"
            prompt: "Broadcast message: Interface naming mode has changed. Users running 'sonic-cli' are required to restart your session."
            answer: "\n"

    - name: "reset ssh connection"
      meta: reset_connection

    - name: "Configure description for interface in standard name"
      dellemc.enterprise_sonic.sonic_config:
        commands:
          - description Eth1/1
        parents:
          - interface Eth1/1
