---
- name: Ansible resource module example for sonic_system
  hosts: datacenter
  gather_facts: false
  connection: ansible.netcommon.httpapi

  tasks:
    - name: Test SONiC system
      dellemc.enterprise_sonic.sonic_system:
        config:
          hostname: SONIC-test
          interface_naming: standard
          anycast_address:
            ipv4: true
            ipv6: true
            mac_address: 00:09:5B:EC:EE:F2
        state: merged
